//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contractor.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contractor.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\contractor-net\BCTBinaries\BytecodeTranslator.exe.
        /// </summary>
        internal static string BCTPath {
            get {
                return ResourceManager.GetString("BCTPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -show errors -show progress -sortwarns=false -warninglevel=full -stats=!! -nobox -nologo -nopex -assemblyMode=standard -suggest=!! -wp -adaptive -arithmetic -bounds -enum -nonnull -typeNameSelect=@fullTypeName -libPaths:&quot;@libPaths&quot; &quot;@assemblyName&quot;.
        /// </summary>
        internal static string CheckerArguments {
            get {
                return ResourceManager.GetString("CheckerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @codeContracts\Bin\cccheck.exe.
        /// </summary>
        internal static string CheckerFileName {
            get {
                return ResourceManager.GetString("CheckerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\contractor-net\CorralBinaries\corral.exe.
        /// </summary>
        internal static string CorralPath {
            get {
                return ResourceManager.GetString("CorralPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			@windows\Microsoft.NET\Framework\v2.0.50727\;
        ///			@windows\Microsoft.NET\Framework\v2.0.50727\CodeContracts;
        ///			@codeContracts\PublicAssemblies\v3.5\;
        ///			@codeContracts\PublicAssemblies\v3.5\CodeContracts;
        ///			@codeContracts\Contracts\v3.5
        ///		.
        /// </summary>
        internal static string Netv20 {
            get {
                return ResourceManager.GetString("Netv20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			@windows\Microsoft.NET\Framework\v2.0.50727\;
        ///			@windows\Microsoft.NET\Framework\v2.0.50727\CodeContracts;
        ///			@codeContracts\PublicAssemblies\v3.5\;
        ///			@codeContracts\PublicAssemblies\v3.5\CodeContracts;
        ///			@codeContracts\Contracts\v3.5
        ///		.
        /// </summary>
        internal static string Netv30 {
            get {
                return ResourceManager.GetString("Netv30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			@windows\Microsoft.NET\Framework\v2.0.50727\;
        ///			@windows\Microsoft.NET\Framework\v2.0.50727\CodeContracts;
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\v3.5\;
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\v3.5\CodeContracts;
        ///			@codeContracts\PublicAssemblies\v3.5\;
        ///			@codeContracts\PublicAssemblies\v3.5\CodeContracts;
        ///			@codeContracts\Contracts\v3.5
        ///		.
        /// </summary>
        internal static string Netv35 {
            get {
                return ResourceManager.GetString("Netv35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\;
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\CodeContracts;
        ///			@codeContracts\PublicAssemblies\v3.5\;
        ///			@codeContracts\PublicAssemblies\v3.5\CodeContracts;
        ///			@codeContracts\Contracts\v3.5
        ///		.
        /// </summary>
        internal static string Netv35ClientProfile {
            get {
                return ResourceManager.GetString("Netv35ClientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\;
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\CodeContracts;
        ///			@codeContracts\Contracts\.NETFramework\v4.0
        ///		.
        /// </summary>
        internal static string Netv40 {
            get {
                return ResourceManager.GetString("Netv40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\;
        ///			@programFiles\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\CodeContracts;
        ///			@codeContracts\Contracts\.NETFramework\v4.0
        ///		.
        /// </summary>
        internal static string Netv40ClientProfile {
            get {
                return ResourceManager.GetString("Netv40ClientProfile", resourceCulture);
            }
        }
    }
}
