using System;
using Contractor.Core;
using System.Collections.Generic;

namespace Contractor.Core
{
    class CorralMock
    {
        #region VendingMachine Queries
        const string VendingQueries = @"STATE$ctorSystemVoid~ctorSystemVoid~BuySystemUInt32SystemUInt32SystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~_Not_BuySystemUInt32SystemUInt32SystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~DisplayPriceSystemUInt32SystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~_Not_DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~ReturnChangeSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~_Not_ReturnChangeSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~ReturnItemSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~_Not_ReturnItemSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~_Not_BuySystemUInt32SystemUInt32SystemVoid NoBugs
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~_Not_DisplayPriceSystemUInt32SystemVoid NoBugs
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~ReturnChangeSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~_Not_ReturnChangeSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~ReturnItemSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~_Not_ReturnItemSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~STATE$deadlock TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~STATE$ReturnChangeSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~STATE$ReturnItemSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid~STATE$ReturnChangeSystemVoid$ReturnItemSystemVoid NoBugs
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~BuySystemUInt32SystemUInt32SystemVoid NoBugs
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~_Not_BuySystemUInt32SystemUInt32SystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid NoBugs
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~_Not_DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~ReturnChangeSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~_Not_ReturnChangeSystemVoid NoBugs
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~ReturnItemSystemVoid TrueBug
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~_Not_ReturnItemSystemVoid NoBugs
STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid~DisplayPriceSystemUInt32SystemVoid~STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~BuySystemUInt32SystemUInt32SystemVoid NoBugs
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~_Not_BuySystemUInt32SystemUInt32SystemVoid TrueBug
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~DisplayPriceSystemUInt32SystemVoid NoBugs
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~_Not_DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~ReturnChangeSystemVoid TrueBug
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~_Not_ReturnChangeSystemVoid NoBugs
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~ReturnItemSystemVoid TrueBug
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~_Not_ReturnItemSystemVoid NoBugs
STATE$ReturnItemSystemVoid~ReturnItemSystemVoid~STATE$BuySystemUInt32SystemUInt32SystemVoid$DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~BuySystemUInt32SystemUInt32SystemVoid TrueBug
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~_Not_BuySystemUInt32SystemUInt32SystemVoid NoBugs
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~DisplayPriceSystemUInt32SystemVoid TrueBug
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~_Not_DisplayPriceSystemUInt32SystemVoid NoBugs
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~ReturnChangeSystemVoid TrueBug
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~_Not_ReturnChangeSystemVoid NoBugs
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~ReturnItemSystemVoid NoBugs
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~_Not_ReturnItemSystemVoid TrueBug
STATE$ReturnChangeSystemVoid~ReturnChangeSystemVoid~STATE$ReturnItemSystemVoid TrueBug";
#endregion

        #region Linear Queries
        const string LinearQueries = @"STATE$ctorSystemVoid~ctorSystemVoid~a0SystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~_Not_a0SystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~a1SystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~_Not_a1SystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~a2SystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~_Not_a2SystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~get_NSystemInt32 NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~_Not_get_NSystemInt32 TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~STATE$a0SystemVoid$get_NSystemInt32 TrueBug
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~a0SystemVoid NoBugs
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a0SystemVoid TrueBug
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~a1SystemVoid TrueBug
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a1SystemVoid NoBugs
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~a2SystemVoid TrueBug
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a2SystemVoid NoBugs
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~get_NSystemInt32 NoBugs
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_get_NSystemInt32 TrueBug
STATE$a0SystemVoid$get_NSystemInt32~get_NSystemInt32~STATE$a0SystemVoid$get_NSystemInt32 TrueBug
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~a0SystemVoid TrueBug
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~_Not_a0SystemVoid NoBugs
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~a1SystemVoid NoBugs
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~_Not_a1SystemVoid TrueBug
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~a2SystemVoid TrueBug
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~_Not_a2SystemVoid NoBugs
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~get_NSystemInt32 NoBugs
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~_Not_get_NSystemInt32 TrueBug
STATE$a0SystemVoid$get_NSystemInt32~a0SystemVoid~STATE$a1SystemVoid$get_NSystemInt32 TrueBug
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~a0SystemVoid TrueBug
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a0SystemVoid NoBugs
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~a1SystemVoid NoBugs
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a1SystemVoid TrueBug
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~a2SystemVoid TrueBug
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a2SystemVoid NoBugs
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~get_NSystemInt32 NoBugs
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_get_NSystemInt32 TrueBug
STATE$a1SystemVoid$get_NSystemInt32~get_NSystemInt32~STATE$a1SystemVoid$get_NSystemInt32 TrueBug
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~a0SystemVoid TrueBug
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~_Not_a0SystemVoid NoBugs
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~a1SystemVoid TrueBug
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~_Not_a1SystemVoid NoBugs
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~a2SystemVoid NoBugs
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~_Not_a2SystemVoid TrueBug
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~get_NSystemInt32 NoBugs
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~_Not_get_NSystemInt32 TrueBug
STATE$a1SystemVoid$get_NSystemInt32~a1SystemVoid~STATE$a2SystemVoid$get_NSystemInt32 TrueBug
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~a0SystemVoid TrueBug
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a0SystemVoid NoBugs
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~a1SystemVoid TrueBug
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a1SystemVoid NoBugs
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~a2SystemVoid NoBugs
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_a2SystemVoid TrueBug
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~get_NSystemInt32 NoBugs
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~_Not_get_NSystemInt32 TrueBug
STATE$a2SystemVoid$get_NSystemInt32~get_NSystemInt32~STATE$a2SystemVoid$get_NSystemInt32 TrueBug
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~a0SystemVoid TrueBug
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~_Not_a0SystemVoid NoBugs
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~a1SystemVoid TrueBug
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~_Not_a1SystemVoid NoBugs
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~a2SystemVoid TrueBug
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~_Not_a2SystemVoid NoBugs
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~get_NSystemInt32 NoBugs
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~_Not_get_NSystemInt32 TrueBug
STATE$a2SystemVoid$get_NSystemInt32~a2SystemVoid~STATE$get_NSystemInt32 TrueBug
STATE$get_NSystemInt32~get_NSystemInt32~a0SystemVoid TrueBug
STATE$get_NSystemInt32~get_NSystemInt32~_Not_a0SystemVoid NoBugs
STATE$get_NSystemInt32~get_NSystemInt32~a1SystemVoid TrueBug
STATE$get_NSystemInt32~get_NSystemInt32~_Not_a1SystemVoid NoBugs
STATE$get_NSystemInt32~get_NSystemInt32~a2SystemVoid TrueBug
STATE$get_NSystemInt32~get_NSystemInt32~_Not_a2SystemVoid NoBugs
STATE$get_NSystemInt32~get_NSystemInt32~get_NSystemInt32 NoBugs
STATE$get_NSystemInt32~get_NSystemInt32~_Not_get_NSystemInt32 TrueBug
STATE$get_NSystemInt32~get_NSystemInt32~STATE$get_NSystemInt32 TrueBug";
        #endregion

        #region Door Queries
        const string DoorQueries = @"STATE$ctorSystemVoid~ctorSystemVoid~AlarmSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~CloseSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~OpenSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~_Not_OpenSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~SafeSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~StartSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~_Not_StartSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~StopSystemVoid TrueBug
STATE$ctorSystemVoid~ctorSystemVoid~_Not_StopSystemVoid NoBugs
STATE$ctorSystemVoid~ctorSystemVoid~STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~StartSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~_Not_StartSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~StopSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~_Not_StopSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~StartSystemVoid~STATE$AlarmSystemVoid$StopSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~_Not_CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~StartSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~_Not_StartSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~StopSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~_Not_StopSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~OpenSystemVoid~STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~StartSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_StartSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~StopSystemVoid TrueBug
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_StopSystemVoid NoBugs
STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid~AlarmSystemVoid~STATE$SafeSystemVoid$StartSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~_Not_OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~StartSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~_Not_StartSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~StopSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~_Not_StopSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~StopSystemVoid~STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~StartSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_StartSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~StopSystemVoid NoBugs
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_StopSystemVoid TrueBug
STATE$AlarmSystemVoid$StopSystemVoid~AlarmSystemVoid~STATE$SafeSystemVoid$StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~_Not_OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~StartSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~_Not_StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~_Not_StopSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~CloseSystemVoid~STATE$AlarmSystemVoid$OpenSystemVoid$StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~_Not_StartSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~StopSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~_Not_StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~StartSystemVoid~STATE$AlarmSystemVoid$StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~StartSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~_Not_StopSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid~AlarmSystemVoid~STATE$SafeSystemVoid$StartSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~AlarmSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~CloseSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~_Not_CloseSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~OpenSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~SafeSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~StartSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~_Not_StartSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~StopSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~_Not_StopSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~SafeSystemVoid~STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~AlarmSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~_Not_AlarmSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~CloseSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~OpenSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~SafeSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~_Not_SafeSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~StartSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~_Not_StartSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~StopSystemVoid NoBugs
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~_Not_StopSystemVoid TrueBug
STATE$SafeSystemVoid$StartSystemVoid~StartSystemVoid~STATE$SafeSystemVoid$StopSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~AlarmSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~CloseSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~_Not_CloseSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~OpenSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~SafeSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~StartSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~_Not_StartSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~StopSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~_Not_StopSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~SafeSystemVoid~STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~AlarmSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~_Not_AlarmSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~CloseSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~OpenSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~SafeSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~_Not_SafeSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~StartSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~_Not_StartSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~StopSystemVoid TrueBug
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~_Not_StopSystemVoid NoBugs
STATE$SafeSystemVoid$StopSystemVoid~StopSystemVoid~STATE$SafeSystemVoid$StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~_Not_StartSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~StopSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~_Not_StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~CloseSystemVoid~STATE$AlarmSystemVoid$StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~_Not_AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~_Not_CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~_Not_SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~StartSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~_Not_StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~_Not_StopSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~StopSystemVoid~STATE$AlarmSystemVoid$CloseSystemVoid$StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~AlarmSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_AlarmSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~CloseSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_CloseSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~OpenSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_OpenSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~SafeSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_SafeSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~StartSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_StartSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~StopSystemVoid NoBugs
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~_Not_StopSystemVoid TrueBug
STATE$AlarmSystemVoid$CloseSystemVoid$StopSystemVoid~AlarmSystemVoid~STATE$SafeSystemVoid$StopSystemVoid TrueBug";
        #endregion

        #region FiniteStack Queries
        const string FiniteStackQueries = @"STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~get_MaxSystemInt32 NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~_Not_get_MaxSystemInt32 TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~get_NextSystemInt32 NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~_Not_get_NextSystemInt32 TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~PopSystemVoid TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~_Not_PopSystemVoid NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~PushSystemInt32SystemVoid NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~_Not_PushSystemInt32SystemVoid TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~get_MaxSystemInt32 NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~_Not_get_MaxSystemInt32 TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~get_NextSystemInt32 NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~_Not_get_NextSystemInt32 TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~PopSystemVoid TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~_Not_PopSystemVoid NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~PushSystemInt32SystemVoid NoBugs
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~_Not_PushSystemInt32SystemVoid TrueBug
STATE$ctorSystemInt32SystemVoid$ctorSystemVoid~ctorSystemInt32SystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_MaxSystemInt32~STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid~get_NextSystemInt32~STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_MaxSystemInt32~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PushSystemInt32SystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~PopSystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid~get_NextSystemInt32~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~_Not_PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_MaxSystemInt32~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~_Not_PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~PopSystemVoid~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid$PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~get_MaxSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~_Not_get_MaxSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~get_NextSystemInt32 NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~_Not_get_NextSystemInt32 TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~PopSystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~_Not_PopSystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~PushSystemInt32SystemVoid TrueBug
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~_Not_PushSystemInt32SystemVoid NoBugs
STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid~get_NextSystemInt32~STATE$get_MaxSystemInt32$get_NextSystemInt32$PopSystemVoid TrueBug";
        #endregion

        Dictionary<string, ResultKind> queries;

        protected ResultKind result;
        public ResultKind Result { get { return result; } }

        public CorralMock()
        {
            this.queries = new Dictionary<string, ResultKind>();
            var allTheQueries = VendingQueries + Environment.NewLine + 
                                LinearQueries + Environment.NewLine + 
                                DoorQueries + Environment.NewLine + 
                                FiniteStackQueries;
            var output = allTheQueries.Replace(Environment.NewLine, "\n").Split('\n');
            foreach (var line in output)
            {
                var result = line.Split(' ');
                    
                switch (result[1])
                {
                    case "NoBugs":
                        queries.Add(result[0], ResultKind.NoBugs);
                        break;
                    case "TrueBug":
                        queries.Add(result[0], ResultKind.TrueBug);
                        break;
                    case "RecursionBoundReached":
                        queries.Add(result[0], ResultKind.RecursionBoundReached);
                        break;
                    default:
                        throw new Exception();
                }
            }
        }

        public TimeSpan Run(string args)
        {
            var queryName = args.Split(' ')[1].Replace("/main:", "");
            if (!queries.ContainsKey(queryName))
            {
                throw new Exception("Query not recognized");
            }
            
            this.result = queries[queryName];

            return new TimeSpan();
        }
    }
}
